In [2]:
# numpy mainly used for creating n-dimensional array
# install numpy 
# from jupyter - pip install numpy
# from cmd - python -m pip install numpy

In [10]:
import numpy as np

a = [16,27,35,81]

arr1 = np.array(a) # create a numpy array

print(arr1)

print(type(arr1)) # ndarray

[16 27 35 81]
<class 'numpy.ndarray'>


In [11]:
b = [29,83,68,92]

arr2 = np.array(b)

print(arr2)

[29 83 68 92]


In [12]:
# using '+' operator on an numpy array
print(a+b) # results in concatenation

print(arr1+arr2) # results in matrix addition

[16, 27, 35, 81, 29, 83, 68, 92]
[ 45 110 103 173]


In [13]:
# numpy array - shape attribute
arr1 = np.array([29,83,68,92])

print(arr1.shape) # number of elements in the array

(4,)


In [15]:
arr1 = np.array(
    [
     [29,83,68,92],
     [16,27,35,81],
    ]
)

print(arr1.shape) # returns (2,4)

(3, 4)


In [16]:
arr1 = np.array(
    [
        [
            [29,83,68,92],
            [16,27,35,81],
            
        ],
        [
            [29,83,68,92],
            [16,27,35,81],
        ]
    ]
    
)

print(arr1.shape)

(2, 2, 4)


In [17]:
# initialize array using zeros or ones

arr1 = np.zeros((2,3))

print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
arr1 = np.ones((2,3))

print(arr1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [20]:
# create a sequence of number between a small range
# linspace - generates numbers between a small range

arr1 = np.linspace(0,.2,30)

print(arr1)

[0.         0.00689655 0.0137931  0.02068966 0.02758621 0.03448276
 0.04137931 0.04827586 0.05517241 0.06206897 0.06896552 0.07586207
 0.08275862 0.08965517 0.09655172 0.10344828 0.11034483 0.11724138
 0.12413793 0.13103448 0.13793103 0.14482759 0.15172414 0.15862069
 0.16551724 0.17241379 0.17931034 0.1862069  0.19310345 0.2       ]
